### ISSUE TITLE
Issues with Middleman

### ISSUE THREAD

**Issue by andreamoro** [charliesome/better_errors#373] opened 2017-05-15 17:05 UTC
Not a great expert of Ruby, so I can't be more precise than this. However, after the activation I can only see an "internal server error" page with the error, but nothing more useful than that.

Paradoxically, the standard error is more useful at this stage as I can at least see the line number.

Any help?

**Comment by RobinDaugherty** [comment] 2017-07-29 05:33
@andreamoro did you add better_errors to your Gemfile? What version of the gem do you have? Does this project use Rails? If it is Rails, can you provide the contents of your `logs/development.log` file?

**Comment by RobinDaugherty** [comment] 2017-07-30 20:22
Duplicate of #301.

**Closed by RobinDaugherty** 2017-07-30 20:22 UTC
Labels: ruby-frameworks
