### ISSUE TITLE
Rails 5 rendering errors raise EOFError

### ISSUE THREAD

**Issue by mysmallidea** [charliesome/better_errors#330] opened 2015-12-29 22:55 UTC
When using better_errors with Rails 5 (beta 1), errors raised in ERB or HAML templates always result in EOFError. 

Not sure if it has something to do with Nack or Pow, but the error raises correctly if better_errors is removed. 

Here's the full stacktrace: 

```
UNIXSocket#read_nonblock
<internal:prelude>, line 76
block (2 levels) in Nack::Server#start
/Users/ryenski/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb, line 107
block in Nack::Server#start
/Users/ryenski/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb, line 96
Nack::Server#start
/Users/ryenski/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb, line 76
Nack::Server.run
/Users/ryenski/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb, line 12
<main>
/Users/ryenski/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/bin/nack_worker, line 4
```

![eoferror](https://cloud.githubusercontent.com/assets/234/12043632/8077d82a-ae4c-11e5-9374-ae6eed7e3774.png)

![eoferror-erb](https://cloud.githubusercontent.com/assets/234/12043648/a72eee68-ae4c-11e5-9d83-f1068cb8a5aa.png)

**Comment by juice** [comment] 2017-03-10 12:12
If someone finds a fix, please let us know.

**Comment by RobinDaugherty** [comment] 2017-07-29 06:39
This is caused by the bug in nack (part of Pow) fixed in https://github.com/josh/nack/pull/42.

**Closed by RobinDaugherty** 2017-07-29 06:39 UTC

**Comment by coneybeare** [comment] 2018-09-27 19:59
Nack is not being maintained anymore, is there a workaround?

**Comment by rmm5t** [comment] 2018-09-28 12:15
@coneybeare Pow is effectively deprecated and obsolete. Consider puma-dev instead. 

https://github.com/puma/puma-dev
