### ISSUE TITLE
undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by maxgronlund** [charliesome/better_errors#305] opened 2015-05-19 07:21 UTC
Extracted source (around line #127):
better_errors (2.1.1) lib/better_errors/middleware.rb:127:in `internal_call'

```
def internal_call(env, opts) <<<<<<<<<<<<<<<<<<<<<<<<<<<<< line 127
  if opts[:id] != @error_page.id
    return [200, { "Content-Type" => "text/plain; charset=utf-8" }, [JSON.dump(error: "Session expired")]]
  end
```

**Comment by sivunestori** [comment] 2015-05-28 21:15
I'm facing the same issue. @error_page is nil. Tried with versions 1.1.0, 2.1.0 and 2.2.0. Issue #301 seems to be related.

**Comment by techsethi** [comment] 2015-10-06 01:16
Having the same issue. Using better_errors with middleman.

**Comment by bfaloona** [comment] 2016-01-09 21:16
Is this a duplicate of issue #301 ?

**Comment by grekko** [comment] 2016-03-31 14:54
@techsethi I may have a fix, see my comment in #301

**Comment by RobinDaugherty** [comment] 2017-07-30 20:21
Duplicate of #301.

**Closed by RobinDaugherty** 2017-07-30 20:21 UTC
